In [32]:
from deepdirect.model import build_aa_mutator, decode_seq_int
from tensorflow.keras import backend as K
import deepdirect
import pickle
import numpy as np

In [6]:
# Load input data
# List of file names
file_names = ['pre.pkl', 'rbd.pkl', 'same.pkl', 'x.pkl', 'y.pkl', 'z.pkl', 'noise.pkl']

input_data = []
# Load data from each pickle file
for file_name in file_names:
    with open("./demo_data/" + file_name, 'rb') as file:
        input_data.append(pickle.load(file)) 

In [5]:
# pre
# protein to be mutated with one-hot encoding
input_data[0]

<tf.Tensor: shape=(1, 3924, 20), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [9]:
# rbd
# rbd index of the protein complex
input_data[1]

<tf.Tensor: shape=(1, 3924, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [8]:
# same
# index of amino acids for the binding proteins
input_data[2]

<tf.Tensor: shape=(1, 3924, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [10]:
# x/y/z
# amino acids' 3D coordinates
# here is example of the x
input_data[3]

<tf.Tensor: shape=(1, 3924, 1), dtype=float32, numpy=
array([[[ 0.04882129],
        [ 0.04745764],
        [ 0.04641467],
        ...,
        [-0.00733794],
        [-0.00811643],
        [-0.00940997]]], dtype=float32)>

In [11]:
# noise
# randome noise for deepdirect
input_data[6]

<tf.Tensor: shape=(1, 3924, 1), dtype=float32, numpy=
array([[[ 0.4595082 ],
        [-1.4272584 ],
        [-0.7729255 ],
        ...,
        [-1.5791382 ],
        [ 0.7828522 ],
        [ 0.35127756]]], dtype=float32)>

In [30]:
# Build amino acid mutator
aa_mutator = build_aa_mutator()

# Load pre-trained weights for model i
aa_mutator.load_weights(deepdirect.weights_i)

# Predict mutataions
predict_result = aa_mutator.predict(input_data)

1/1 [==============================] - 3s 3s/step


In [31]:
# Obtain mutated sequence by argmax
aft = K.argmax(predict_result, axis=-1).numpy()[0]
aft

array([11, 17, 10, ..., 12, 12, 12])